#!/bin/bash
# simple update notifier
# a very simplistic update notification script written 
# in bash, using notify-send and kdialog. 

pacmanconf=/etc/pacman.conf

main() {

}

isignored() {
  IFS=$'\n'" "
  local ignoredpkgs=( $(grep '^ *IgnorePkg' "$pacmanconf" | cut -d '=' -f 2-) )
  IFS=' '
  grep -q "^$1$" <<< "${ignoredpkgs[@]}"
}

daemon() {

}

gui() {

}

dothings() {

}

