#!/bin/bash

enable() {
    echo "Adding spun to autostart apps..."
    cat > /usr/share/autostart/spun.desktop << EOF
[Desktop Entry]
Exec=spun
Icon=system-software-update
Type=Application
Terminal=false
X-KDE-autostart-after=panel
X-KDE-StartupNotify=false
X-DBUS-StartupType=Unique
X-KDE-UniqueApplet=true
Categories=KDE;System;
Name=spun
GenericName=Update Notifier
EOF
    echo "Done. Press Enter to continue."
    read me
    exit 0
}

disable() {
    echo "Removing spun from autostart apps..."
    [[ -f /usr/share/autostart/spun.desktop ]] &&
        rm /usr/share/autostart/spun.desktop
    echo "Done. Press Enter to continue."
    read me
    exit 0
}

if ! [[ $UID == 0 || $EUID == 0 ]]; then
    # not root
    echo "must be root"
    exit 1
fi

if [[ $1 == "enable" ]]; then
    enable
elif [[ $1 == "disable" ]]; then
    disable
else
    echo "usage: spun-autostart [enable|disable]"
    exit 1
fi
